[Greeter]
WallpaperPlugin=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image=file:///usr/share/wallpapers/Dracula/school-of-athens.jpg
PreviewImage=file:///usr/share/wallpapers/Dracula/school-of-athens.jpg
